
// INSERT HERE YOUR CUSTOM CONSTANTS




// START CRUD CONSTANTS

// ITEMS
export const CREATE_ITEMS_SUCCESS = "CREATE_ITEMS_SUCCESS";
export const DELETE_ITEMS_SUCCESS = "DELETE_ITEMS_SUCCESS";
export const GET_ITEMS_SUCCESS = "GET_ITEMS_SUCCESS";
export const LIST_ITEMS_SUCCESS = "LIST_ITEMS_SUCCESS";
export const UPDATE_ITEMS_SUCCESS = "UPDATE_ITEMS_SUCCESS";

// ORDER
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const DELETE_ORDER_SUCCESS = "DELETE_ORDER_SUCCESS";
export const GET_ORDER_SUCCESS = "GET_ORDER_SUCCESS";
export const LIST_ORDER_SUCCESS = "LIST_ORDER_SUCCESS";
export const UPDATE_ORDER_SUCCESS = "UPDATE_ORDER_SUCCESS";

// ORDERDETAILS
export const CREATE_ORDERDETAILS_SUCCESS = "CREATE_ORDERDETAILS_SUCCESS";
export const DELETE_ORDERDETAILS_SUCCESS = "DELETE_ORDERDETAILS_SUCCESS";
export const GET_ORDERDETAILS_SUCCESS = "GET_ORDERDETAILS_SUCCESS";
export const LIST_ORDERDETAILS_SUCCESS = "LIST_ORDERDETAILS_SUCCESS";
export const UPDATE_ORDERDETAILS_SUCCESS = "UPDATE_ORDERDETAILS_SUCCESS";

// USER
export const CHANGEPASSWORD_USER_SUCCESS = "CHANGEPASSWORD_USER_SUCCESS";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const LIST_USER_SUCCESS = "LIST_USER_SUCCESS";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";

// CUSTOMER
export const CREATE_CUSTOMER_SUCCESS = "CREATE_CUSTOMER_SUCCESS";
export const DELETE_CUSTOMER_SUCCESS = "DELETE_CUSTOMER_SUCCESS";
export const GET_CUSTOMER_SUCCESS = "GET_CUSTOMER_SUCCESS";
export const LIST_CUSTOMER_SUCCESS = "LIST_CUSTOMER_SUCCESS";
export const UPDATE_CUSTOMER_SUCCESS = "UPDATE_CUSTOMER_SUCCESS";

// END CRUD CONSTANTS

// USER
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_ADMIN_SUCCESS = "CHANGE_PASSWORD_ADMIN_SUCCESS";
